Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/08/2020
Var
numero: real
Inicio
escreval ("Escolha um numero")
leia (numero)
se numero mod 2 = 0 entao
escreval ("O numero ", numero, " é par")
senao
escreval ("O numero ", numero, " é impar")
fimse
Fimalgoritmo