Algoritmo "exercicio7"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
Var
 temperaturax : inteiro
 temperaturay : inteiro
 temperaturaambiente: caractere
Inicio
escreval ("qual a temperatura ambiente?")
leia (temperaturaambiente)

se (temperaturaambiente > "25") entao
 escreval ("esta muito quente")
 senao
 escreval ("esta agradavel")
 fimse

fimalgoritmo