Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/08/2020
Var
numero, cont: inteiro
Inicio
numero <- 2

Enquanto (numero <= 2) faca
para cont de 2 até 100 passo 2 faca
escreval (cont)
fimpara
numero  <- numero + 1
Fimenquanto
Fimalgoritmo