Algoritmo "exercicio11"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
Var
notax: real
notay: real
notaz: real
resultado: real


Inicio
escreval("primeira nota")
leia (notax)

escreval ("segunda nota")
leia (notay)

escreval ("terceira nota")
leia (notaz)



                  caso problema = "somar" faca
      resultado <- (notax*2+notay*3+notaz*5)/10
       escreval (resultado)
          

fimalgoritmo

